En esta jupyter-notebook vamos a desmenuzar de a poco el código de Dondorp.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import ipyvolume as ipv
from ipywidgets import interact, interact_manual, widgets

La libreria ipyvolume nos da herramientas para visualizar volúmenes en 3D. La libreria ipywidgets nos brinda herramientas interactivas para agregar a las jupyter-notebooks.

In [3]:
def make_box(box_size, space_size = None):
    if not space_size:
        space_size = box_size + 100
    box = np.zeros([space_size for x in range(3)])
    start = (space_size - box_size) // 2
    end = space_size - start
    box[start:end, start:end, start:end] = 1
    return(box)

In [4]:
box = make_box(box_size=200)

Aqui define una función que nos devuelve una caja tridimensional (matriz tridimensional) llena de 1s de tamaño box_size centrada en una caja tridimensional (matriz tridimensional) llena de 0s de tamaño space_size.
En la matriz tridimensional la caja que creamos estará centrada siempre que no definamos explicitamente el valor de space_size; si lo definimos creo que no necesariamente estará centrada.

Utilicemos como ejemplo la misma función pero con space_size = box_size + 2:

In [5]:
def make_box1(box_size, space_size = None):
    if not space_size:
        space_size = box_size + 2
    box = np.zeros([space_size for x in range(3)])
    start = (space_size - box_size) // 2
    end = space_size - start
    box[start:end, start:end, start:end] = 1
    return(box)

In [6]:
box1 = make_box1(box_size=2)
print(box1)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 1. 1. 0.]
  [0. 1. 1. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 1. 1. 0.]
  [0. 1. 1. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [7]:
locs = np.where(box > 0)
pixels = [(x,y,z) for x,y,z in zip(*locs)]
pixels = np.array(pixels)
print(pixels.shape)

(8000000, 3)


Esta linea de código lo que hace es:
- Con np.where(box>0) arma una lista con tres arrays que contienen las coordenadas (x,y,z) de cada valor distinto de 0. O sea el primer array tiene las coordenadas x de todos los elementos de la caja que armamos, el segundo array contiene a las coordenadas 'y' y el tercer array tiene las coordenadas z.
- Con zip(* locs) arma ternas utilizando los arrays de la lista locs.
- Con np.array(pixels) arma un array bidimensional (una matriz) cuyas filas contienen las coordenadas de los puntos de la caja tridimensional.
- pixels.shape nos da como resultado (8000000,3) que quiere decir que tenemos dos dimensiones, la primera con la cantidad de puntos que tiene la caja y el tercero con la cantidad de coordenadas, que obviamente debe ser 3.

Para ver que nos da estas lineas de código vamos a tomar como ejemplo la caja box1:

In [8]:
locs = np.where(box1 > 0)
pixels = [(x,y,z) for x,y,z in zip(*locs)]
print(pixels)
print()
pixels = np.array(pixels)
print(pixels)
print()
print(pixels.shape)

[(1, 1, 1), (1, 1, 2), (1, 2, 1), (1, 2, 2), (2, 1, 1), (2, 1, 2), (2, 2, 1), (2, 2, 2)]

[[1 1 1]
 [1 1 2]
 [1 2 1]
 [1 2 2]
 [2 1 1]
 [2 1 2]
 [2 2 1]
 [2 2 2]]

(8, 3)


Vemos que en box1 solo tenemos 8 elementos distintos de 0 y con esta linea de códigos obtenemos las coordenadas de todos esos puntos. pixels.shape nos dice que tenemos 8 posiciones y 3 coordenadas para cada posición.

In [16]:
print(box1)
print()
print(box.shape)
print()
print(np.min(box1.shape))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 1. 1. 0.]
  [0. 1. 1. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 1. 1. 0.]
  [0. 1. 1. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

(300, 300, 300)

4


In [14]:
exponent_data = np.log(np.min(box.shape)) / np.log(2)
print(exponent_data)
print()
largest_box_size_exponent = int(np.floor(exponent_data))
print(largest_box_size_exponent)
print()
print(np.floor(exponent_data))
print()
print(f"largest_box_size = {2**largest_box_size_exponent}")

8.228818690495881

8

8.0

largest_box_size = 256


In [20]:
largest_exponent = int(np.floor(np.log2(np.min(box.shape))))
print(f"largest_exponent = {largest_exponent}, box_size = {2**largest_exponent}")
np.log2(np.min(box.shape))

largest_exponent = 8, box_size = 256


8.228818690495881

In [21]:
scales = [2**x for x in range(largest_exponent, 1, -1)]
print(scales)

[256, 128, 64, 32, 16, 8, 4]
